### PR TITLE
Added a new file"IPL_SCORE_VIEWER" in coding --> python folder 

### PR DESCRIPTION
**Pull request by sarthakd999**

### CODE REVIEW

**Comment by sarthakd999** [comment]
This project is based on  --> bs4 and pycricbuzz

so you will need to install both the packages
@ArshdeepSahni

**Comment by ArshdeepSahni** [comment]
Please star the repo 🌟

**Comment by sarthakd999** [comment]
Bro why is ur repo not participating in the Hacktoberfest 2020

My PR is ineligible for hacktoberfest
@ArshdeepSahni

**Comment by sarthakd999** [comment]
Will u please add that repo also for hacktoberfest ???

@ArshdeepSahni

**Comment by ArshdeepSahni** [comment]
Please ask your query on my linkedin please https://www.linkedin.com/in/arshdeep-singh-418a9b194

**Pull request merged**
